SELECT [EmployeeID]
      ,[FirstName]
      ,[LastName]
      ,[Email]
      ,[Phone]
      ,[HireDate]
      ,[JobID]
      ,[Salary]
      ,[Commission_pct]
      ,[ManagerID]
      ,[DepartmentID]
  FROM [dbo].[Employees] WHERE Salary > 9000
